### ISSUE TITLE
running check_Server

### ISSUE THREAD

**Issue by kingroryg** [theSage21/openJudge#3]
First I run , 

```
python3 manage.py runserver 
```

. Webserver runs perfectly at http://127.0.0.1:8000/ .

Then I do 

```
python3 slave.py
```

and this is the error I get ...

```
Anouncing loyalty to the web address
Traceback (most recent call last):
  File "slave.py", line 155, in <module>
    sl = Slave(webaddress)
  File "slave.py", line 58, in __init__
    self.__get_question_details()
  File "slave.py", line 74, in __get_question_details
    page = urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR


```

I also have python3 added to my $PATH .

**Comment by theSage21** [comment]
@saru95 The same is running perfectly on my machine. Can you please specify the python version (3.x) and platform (windows/ linux)

**Comment by kingroryg** [comment]
```
saru95:check_Server sarthakmunshi$ python3 --version
Python 3.4.1
```

Running OSX . Webserver runs perfectly . However this check_server is giving this issue . Can you just in detail specify how to execute this project ?

**Comment by theSage21** [comment]
@saru95 are you running the program with `python slave.py` as opposed to `python3 slave.py`? Python2 does not have `urllib.request` Check with that.

**Comment by kingroryg** [comment]
Im running 
`python3 slave.py` .

**Comment by theSage21** [comment]
Inside the python shell can you import `urllib.request`? If that is also raising errors there is something wrong with the way your python is setup. @libhide Since you work on OSX inputs?

**Comment by kingroryg** [comment]
no error . python3 is added to path too .

**Comment by theSage21** [comment]
@saru95 I am traveling right now. Will get on this when I reach a computer. Meanwhile @libhide can you have an attempt on this?

**Comment by kingroryg** [comment]
yeah , sure .Just for the sake of clarity, do I need a venv image in the project ?

**Comment by theSage21** [comment]
Virtual environment helps.

**Comment by theSage21** [comment]
@saru95 Have you made changes to the codebase? If yes then is there a file called `urllib` in the directory where you are running the code from? Could you also confirm the output of these commands?

```
$ which python3
$ python3 -c 'from urllib.request import urlopen'
```

**Comment by kingroryg** [comment]
```
saru95:~ sarthakmunshi$ which python3
/Library/Frameworks/Python.framework/Versions/3.4/bin/python3
saru95:~ sarthakmunshi$ python3 -c 'from urllib.request import urlopen'
saru95:~ sarthakmunshi$ 
```

No I haven't changed the codebase .

**Comment by theSage21** [comment]
Oh wait. Had a careful look at the traceback.
This one arises from the webserver since there are no languages and questions installed. Do this.

```
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
```
1. Open `localhost/admin` and login. 
2. Upload some languages and questions and try again.

**Comment by kingroryg** [comment]
do you mean python3 manage.py makemigrations ?

**Comment by kingroryg** [comment]
```
saru95:webserver sarthakmunshi$ python3 manage.py makemigrations
No changes detected

saru95:webserver sarthakmunshi$ python3 manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: bootstrapform, question, staticfiles, messages
  Apply all migrations: auth, admin, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table question_profile
    Creating table question_language
    Creating table question_attempt
    Creating table question_question
    Creating table question_answertype
    Creating table question_answer
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'question.Profile'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more
```

```
saru95:webserver sarthakmunshi$ sudo python3 manage.py createsuperuser
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 81, in handle
    default_username = get_default_username()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/contrib/auth/management/__init__.py", line 177, in get_default_username
    auth_app.User._default_manager.get(username=default_username)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
```

**Comment by theSage21** [comment]
As mentioned in the first traceback https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies. You can solve the current issue by running `python manage.py makemigrations question` and `python manage.py makemigraitons contest` before running `python manage.py migrate`.

When the first version is released setup and running of openJudge will be streamlined and put into shell scripts. Complete instructions will be put up. This is currently in beta. 

:smile: Thank you for the interest and feel free to ask for help.

**Comment by kingroryg** [comment]
I get the following result : 

```
saru95:webserver sarthakmunshi$ python3 manage.py makemigrations question
Migrations for 'question':
  0001_initial.py:
    - Create model Answer
    - Create model AnswerType
    - Create model Attempt
    - Create model Language
    - Create model Profile
    - Create model Question
    - Add field language to attempt
    - Add field player to attempt
    - Add field question to attempt
    - Add field answer_type to answer
    - Add field question to answer

saru95:webserver sarthakmunshi$ python3 manage.py makemigrations contest
No changes detected in app 'contest'

saru95:webserver sarthakmunshi$ python3 manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: bootstrapform, messages, staticfiles
  Apply all migrations: contenttypes, admin, question, sessions, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying question.0001_initial...Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "question_answer" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "question_answer" already exists
```

Although running slave.py gives no error, but how do i manipulate the client ip (in this case 0.0.0.0:9000)

```
saru95:check_server sarthakmunshi$ python3 slave.py
Anouncing loyalty to the web address
Slave active at:  ('0.0.0.0', 9000)
```

**Comment by theSage21** [comment]
@saru95 you need to delete that old database which was causing errors and start afresh. `db.sqlite3`.
Just wait for the first release. A few days and it will be out.

**Comment by kingroryg** [comment]
Actually i need it for an event thats supposed to be held on saturday. Hence, the rush .

**Comment by theSage21** [comment]
Hmm. I will try to push by today.

**Comment by theSage21** [comment]
@saru95 Can you pull the latest version? Delete everything and start from a clean folder. Follow the updated README.md

**Comment by kingroryg** [comment]
Ill get right on it .

**Comment by kingroryg** [comment]
Hey man ! i got it working the old way after cloning the repo . thanks !

**Comment by theSage21** [comment]
Glad to know you use it. :smile:
